package com.nmd.eventCalendar.compose.ui.config

import androidx.compose.runtime.Composable
import androidx.compose.runtime.Immutable
import kotlinx.datetime.DayOfWeek
import kotlinx.datetime.LocalDate

/**
 * Configuration options for the calendar UI.
 *
 * @property weekStart The first day of the week used for the calendar grid (e.g., Monday or Sunday).
 * @property headerVisible Whether the calendar header (typically month title / navigation) is visible.
 * @property calendarWeekVisible Whether the calendar week number (ISO week) column is shown.
 * @property minDate Optional lower bound (inclusive). If set, months/days before this date are not selectable/visible
 * (depending on the controller implementation).
 * @property maxDate Optional upper bound (inclusive). If set, months/days after this date are not selectable/visible
 * (depending on the controller implementation).
 * @property openEndedWindowMonths Window size (in months) used when the calendar range is open-ended
 * (i.e., when only one bound is set or when both bounds are null). This value represents the TOTAL number of months
 * that will be generated by the pager for the open-ended case.
 *
 * Example: {@code openEndedWindowMonths = 5 * 12} creates a 60-month window in total (not 5 years into the past AND
 *  * 5 years into the future).
 *
 * @property isCurrentWeekOnly If true, only the current calendar week is displayed.
 * [minDate], [maxDate], and [openEndedWindowMonths] will be ignored in this mode.
 * The calendar will automatically filter the events provided by the [com.nmd.eventCalendar.compose.ui.events.CalendarEventsStore] to only show those that fall within the current week.
 */
@Immutable
data class CalendarOptions(
    val weekStart: DayOfWeek,
    val headerVisible: Boolean,
    val calendarWeekVisible: Boolean,
    val minDate: LocalDate? = null,
    val maxDate: LocalDate? = null,
    val openEndedWindowMonths: Int,
    val isCurrentWeekOnly: Boolean = false,
)

/**
 * Returns the default calendar options.
 *
 * Defaults:
 * - Week starts on Monday
 * - Header is visible
 * - Week number column is hidden
 * - No min/max date bounds
 * - Open-ended window is 5 years (60 months) in total
 * - isCurrentWeekOnly is false
 */
@Composable
fun defaultCalendarOptions(): CalendarOptions {
    return CalendarOptions(
        weekStart = DayOfWeek.MONDAY,
        headerVisible = true,
        calendarWeekVisible = false,
        minDate = null,
        maxDate = null,
        openEndedWindowMonths = 5 * 12,
        isCurrentWeekOnly = false
    )
}